kind: Secret
type: kubernetes.io/dockerconfigjson
apiVersion: v1
metadata:
  name: credential-github
data:
  .dockerconfigjson: ewogICAgImF1dGhzIjoKICAgIHsKICAgICAgICAiZ2hjci5pbyI6CiAgICAgICAgICAgIHsKICAgICAgICAgICAgICAgICJhdXRoIjoiWVdodFlXUnBjbVpoWVc0NloyaHdYMFJFVURReVMwTTBZMlZyT0VOM1YzSllaVWd3WlhWNlJUQkVWMlJEZERGM2NHbHJTQT09IgogICAgICAgICAgICB9CiAgICB9Cn0=